### ISSUE TITLE
[Use Case Diagram] 

### ISSUE THREAD

**Issue by damiecode** [BuildForSDG/Team-238-Frontend#3]
use case diagram at its simplest is a representation of a user's interaction with the system that shows the relationship between the user and the different use cases in which the user is involved.

**Comment by Chibest27** [comment]
How can go about it now

**Comment by damiecode** [comment]
I am currently looking for an app that we can all work on and is not paid. I am also waiting for Imoh he might know one so when he is online I will ask him
